version: '3.5'

services:
  payara:
    image: payara/server-full:5.2022.5-jdk11
    depends_on:
      - kafka
    ports:
      - "5080:8080"
      - "5081:8181"
      - "5048:4848"
      - "5009:5009"
    restart: always
    #    environment:
    #      - AS_ADMIN_PASSWORD=
    volumes:
      - /tmp/payara-apps:/opt/payara/deployments
    networks:
      - greeting-net

  zookeeper:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    restart: always
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - greeting-net

  kafka:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override num.partitions=$${KAFKA_NUM_PARTITIONS} --override group.min.session.timeout.ms=$${KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "59092:59092"
    restart: always
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:59092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:59092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 100
    networks:
      - greeting-net

  akhq:
    image: tchiotludo/akhq:0.23.0
    depends_on:
      - kafka
    ports:
      - "59070:8080"
    restart: always
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
          logging:
            level:
              ROOT: DEBUG
          server:
            context-path: "/akhq"
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:59092"
    networks:
      - greeting-net

networks:
  sample-network:
    name: greeting-net

